### ISSUE TITLE
Python3 compatibility

### ISSUE THREAD

**Issue by tkossak** [lameiro/cx_oracle_on_ctypes#14] opened 2016-10-20 15:20 UTC
I can't get it to run on pypy. I can import original cx_Oracle (using standard python), so i guess all env vars are correctly specified.

```
$ python -c 'import cx_Oracle'
$ export PYTHONPATH=/home/kossak/apps/cx_oracle_on_ctypes

$ pypy -c 'import cx_Oracle'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/__init__.py", line 10, in <module>
    from custom_exceptions import Warning, Error, InterfaceError, DatabaseError, DataError, OperationalError, IntegrityError, InternalError, ProgrammingError, NotSupportedError
ImportError: No module named 'custom_exceptions'

$ python -c 'import cx_Oracle'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/__init__.py", line 10, in <module>
    from custom_exceptions import Warning, Error, InterfaceError, DatabaseError, DataError, OperationalError, IntegrityError, InternalError, ProgrammingError, NotSupportedError
ImportError: No module named 'custom_exceptions'

$ python -V
Python 3.5.2 :: Anaconda 4.2.0 (64-bit)

$ pypy -V
Python 3.3.5 (619c0d5af0e5, Oct 08 2016, 21:08:33)
[PyPy 5.5.0-alpha0 with GCC 4.8.2]

$ ls -l /home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/custom_exceptions.py
-rwxr-xr-x 1 kossak kossak 723 Oct 20 16:13 /home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/custom_exceptions.py*

$ cd /home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle
$ pypy __init__.py
Traceback (most recent call last):
  File "__init__.py", line 10, in <module>
    from custom_exceptions import Warning, Error, InterfaceError, DatabaseError, DataError, OperationalError, IntegrityError, InternalError, ProgrammingError, NotSupportedError
  File "/home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/custom_exceptions.py", line 1, in <module>
    from utils import python3_or_better
  File "/home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/utils.py", line 31, in <module>
    cxString = unicode
NameError: name 'unicode' is not defined

```

I'm on Linux Mint 18 x64 but get the same error on Oracle Linux Server 6.5 x64

**Comment by lameiro** [comment] 2016-10-23 22:49
Hi Kossak.
Your setup is correct. What you see is actually because cx_oracle_on_ctypes is not yet working on Python 3. If you try Python 2, you should have no issues.

In the meantime, I have been working on finishing the port to Python 3 and it is looking very good already. I have a few minor issues to fix but it should be ready in a few days.

I will update this issue when it is done.

**Comment by lameiro** [comment] 2016-10-29 20:52
Hi Kossak.

I got cx_oracle_on_ctypes working on CPython3 (master branch), but it doesn't work on PyPy3 alpha yet. There is some difference in behavior between CPython3 and PyPy 3 when it comes to ctypes. It is not clear if the problem is in cx_oracle_on_ctypes or in PyPy3.

I will have to dive deep into it, I will update this issue in a few days.

**Comment by lameiro** [comment] 2016-10-31 00:05
Hi Kossak,

Please try again with latest master.
All tests are passing with PyPy3.3 v5.5-alpha.

**Comment by tkossak** [comment] 2016-11-02 12:05
I tried it today:

```
$ export PYTHONPATH=/home/kossak/apps/cx_oracle_on_ctypes

$ pypy -c 'import cx_Oracle'
Traceback (most recent call last):
  File "/home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/oci.py", line 2, in <module>
    from cx_Oracle.oci_generated_12 import *
  File "/home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/oci_generated_12.py", line 613, in <module>
    _libs["libclntsh.so.12.1"] = load_library("libclntsh.so.12.1")
  File "/home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/oci_generated_12.py", line 367, in load_library
    raise ImportError("%s not found." % libname)
ImportError: libclntsh.so.12.1 not found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/oci.py", line 5, in <module>
    from cx_Oracle.oci_generated_11 import *
  File "/home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/oci_generated_11.py", line 596, in <module>
    _libs["libclntsh.so.11.1"] = load_library("libclntsh.so.11.1")
  File "/home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/oci_generated_11.py", line 366, in load_library
    raise ImportError("%s not found." % libname)
ImportError: libclntsh.so.11.1 not found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/oci.py", line 8, in <module>
    from cx_Oracle.oci_generated_10 import *
  File "/home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/oci_generated_10.py", line 596, in <module>
    _libs["libclntsh.so.10.1"] = load_library("libclntsh.so.10.1")
  File "/home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/oci_generated_10.py", line 366, in load_library
    raise ImportError("%s not found." % libname)
ImportError: libclntsh.so.10.1 not found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/__init__.py", line 13, in <module>
    from cx_Oracle.connection import Connection
  File "/home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/connection.py", line 4, in <module>
    from cx_Oracle import oci
  File "/home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/oci.py", line 10, in <module>
    raise Exception("Could not import oracle libraries version 12, 11 or 10. Giving up. Don't forget to set your ORACLE_HOME and LD_LIBRARY_PATH.")
Exception: Could not import oracle libraries version 12, 11 or 10. Giving up. Don't forget to set your ORACLE_HOME and LD_LIBRARY_PATH.


$ python -c 'import cx_Oracle'
Traceback (most recent call last):
  File "/home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/oci.py", line 2, in <module>
    from cx_Oracle.oci_generated_12 import *
  File "/home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/oci_generated_12.py", line 613, in <module>
    _libs["libclntsh.so.12.1"] = load_library("libclntsh.so.12.1")
  File "/home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/oci_generated_12.py", line 367, in load_library
    raise ImportError("%s not found." % libname)
ImportError: libclntsh.so.12.1 not found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/oci.py", line 5, in <module>
    from cx_Oracle.oci_generated_11 import *
  File "/home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/oci_generated_11.py", line 596, in <module>
    _libs["libclntsh.so.11.1"] = load_library("libclntsh.so.11.1")
  File "/home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/oci_generated_11.py", line 366, in load_library
    raise ImportError("%s not found." % libname)
ImportError: libclntsh.so.11.1 not found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/oci.py", line 8, in <module>
    from cx_Oracle.oci_generated_10 import *
  File "/home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/oci_generated_10.py", line 596, in <module>
    _libs["libclntsh.so.10.1"] = load_library("libclntsh.so.10.1")
  File "/home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/oci_generated_10.py", line 366, in load_library
    raise ImportError("%s not found." % libname)
ImportError: libclntsh.so.10.1 not found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/__init__.py", line 13, in <module>
    from cx_Oracle.connection import Connection
  File "/home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/connection.py", line 4, in <module>
    from cx_Oracle import oci
  File "/home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/oci.py", line 10, in <module>
    raise Exception("Could not import oracle libraries version 12, 11 or 10. Giving up. Don't forget to set your ORACLE_HOME and LD_LIBRARY_PATH.")
Exception: Could not import oracle libraries version 12, 11 or 10. Giving up. Don't forget to set your ORACLE_HOME and LD_LIBRARY_PATH.


$ export LD_LIBRARY_PATH=/opt/oracle/oracle/product/12.1.0/client_1/lib


$ python -c 'import cx_Oracle'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/__init__.py", line 13, in <module>
    from cx_Oracle.connection import Connection
  File "/home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/connection.py", line 4, in <module>
    from cx_Oracle import oci
  File "/home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/oci.py", line 2, in <module>
    from cx_Oracle.oci_generated_12 import *
  File "/home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/oci_generated_12.py", line 798, in <module>
    Hda_Def = Hda_AlignType * (256 / sizeof(Hda_AlignType)) # /home/lameiro/projects/instantclient/instantclient_12_1/sdk/include/ocidfn.h: 160
TypeError: can't multiply sequence by non-int of type 'float'


$ pypy -c 'import cx_Oracle'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/__init__.py", line 13, in <module>
    from cx_Oracle.connection import Connection
  File "/home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/connection.py", line 4, in <module>
    from cx_Oracle import oci
  File "/home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/oci.py", line 2, in <module>
    from cx_Oracle.oci_generated_12 import *
  File "/home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/oci_generated_12.py", line 798, in <module>
    Hda_Def = Hda_AlignType * (256 / sizeof(Hda_AlignType)) # /home/lameiro/projects/instantclient/instantclient_12_1/sdk/include/ocidfn.h: 160
  File "/opt/pypy3/lib_pypy/_ctypes/basics.py", line 76, in __mul__
    return create_array_type(self, other)
  File "/opt/pypy3/lib_pypy/_ctypes/array.py", line 225, in create_array_type
    raise TypeError("Can't multiply a ctypes type by a non-integer")
TypeError: Can't multiply a ctypes type by a non-integer


```

**Comment by lameiro** [comment] 2016-11-03 02:16
Hi Kossak,

The problem you found would happen only on Oracle 12 with Python 3. Anyway, it is fixed now and the tests run fine on OSX. Couldn't try the other OSes yet but it should work. 

Please give it another try and let me know.

**Comment by tkossak** [comment] 2016-11-03 10:06
It works now, thank you.

One more question: do you know why `cx_oracle_on_ctypes` can't find `libclntsh.so` library? Standard `cx_Oracle` can find it without me manually exporting LD_LIBRARY_PATH (because i have proper path set in `/etc/ld.so.conf.d/oracle.conf`), but somehow `cx_oracle_on_ctypes` ignores this path.

```
$ python -c 'import cx_Oracle'
$ export PYTHONPATH=/home/kossak/apps/cx_oracle_on_ctypes
$ python -c 'import cx_Oracle'
Traceback (most recent call last):
  File "/home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/oci.py", line 2, in <module>
    from cx_Oracle.oci_generated_12 import *
  File "/home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/oci_generated_12.py", line 613, in <module>
    _libs["libclntsh.so.12.1"] = load_library("libclntsh.so.12.1")
  File "/home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/oci_generated_12.py", line 367, in load_library
    raise ImportError("%s not found." % libname)
ImportError: libclntsh.so.12.1 not found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/oci.py", line 5, in <module>
    from cx_Oracle.oci_generated_11 import *
  File "/home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/oci_generated_11.py", line 596, in <module>
    _libs["libclntsh.so.11.1"] = load_library("libclntsh.so.11.1")
  File "/home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/oci_generated_11.py", line 366, in load_library
    raise ImportError("%s not found." % libname)
ImportError: libclntsh.so.11.1 not found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/oci.py", line 8, in <module>
    from cx_Oracle.oci_generated_10 import *
  File "/home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/oci_generated_10.py", line 596, in <module>
    _libs["libclntsh.so.10.1"] = load_library("libclntsh.so.10.1")
  File "/home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/oci_generated_10.py", line 366, in load_library
    raise ImportError("%s not found." % libname)
ImportError: libclntsh.so.10.1 not found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/__init__.py", line 13, in <module>
    from cx_Oracle.connection import Connection
  File "/home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/connection.py", line 4, in <module>
    from cx_Oracle import oci
  File "/home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/oci.py", line 10, in <module>
    raise Exception("Could not import oracle libraries version 12, 11 or 10. Giving up. Don't forget to set your ORACLE_HOME and LD_LIBRARY_PATH.")
Exception: Could not import oracle libraries version 12, 11 or 10. Giving up. Don't forget to set your ORACLE_HOME and LD_LIBRARY_PATH.
$ export LD_LIBRARY_PATH=/opt/oracle/oracle/product/12.1.0/client_1/lib
$ python -c 'import cx_Oracle'
$ echo $?
0

```

**Comment by lameiro** [comment] 2016-11-06 21:18
Hi Kossak,

Thanks for testing it.
For your second issue, I prefer to move to another github issue to keep things organized. I created a new issue to continue this discussion: https://github.com/lameiro/cx_oracle_on_ctypes/issues/15

**Closed by lameiro** 2016-11-06 21:18 UTC
